In [486]:
import numpy as np
import pandas as pd

In [487]:
np_array = np.ones(9)
print(np_array)


np_array_ = np.full(4, 9)
print(np_array_)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 9 9 9]


In [488]:
my_list = [23, 34, 5]
my_list = np.array(my_list)
print(my_list)

[23 34  5]


In [489]:
range_array = np.arange(90)
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [490]:
linspace_array = np.linspace(0,1,3)
linspace_array

array([0. , 0.5, 1. ])

In [491]:
zm = np.full([10, 10], 89)
zm

array([[89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89]])

In [492]:
# slicing function
arr = np.array([[2,3,4], [4, 5, 6]])
print(arr)
arr = arr[1:, 1:]
arr

[[2 3 4]
 [4 5 6]]


array([[5, 6]])

In [493]:
k = np.random.rand(2, 2)
print(k)

m = np.random.randint(0, 10, [2, 2])
print(m)

[[0.67178779 0.38664691]
 [0.6344486  0.69081506]]
[[2 1]
 [2 5]]


In [494]:
g = m > 5
g

array([[False, False],
       [False, False]])

In [495]:
elems = np.random.randint(1, 20, [4, 4])
print(elems)
selected_elements = elems[elems>10]
print(selected_elements)
print(elems.size)

[[10  2  4  4]
 [17 19 11 14]
 [18  7 13  5]
 [ 6  5  8 16]]
[17 19 11 14 18 13 16]
16


In [496]:


data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

df = pd.DataFrame(data)
df.columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]
df


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [497]:
ser = df['Make']
ser

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [498]:
df[["Make", "Model"]]

Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier

In [499]:
df['id'] = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [500]:
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [501]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [502]:
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [503]:
df.index = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1   Nissan    Stanza  1991      138.0                 4            MANUAL   
2  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3    Lotus     Elise  2010      218.0                 4            MANUAL   
4      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
5   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         sedan   2000  
2         Sedan  27150  
3   convertible  54990  
4       4dr SUV  34450  
5        Pickup  32340

In [504]:
pd.__version__

'2.2.3'

## Homework 1 :

In [505]:
df = pd.read_csv('laptops.csv')
print(df.shape)


print("Q2 : 2160")

(2160, 12)
Q2 : 2160


In [506]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [507]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [508]:
print("Q3 : 27")

Q3 : 27


In [509]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [552]:
print("Q4 : 3")

Q4 : 3


In [511]:
df2 = df[df['Brand'] == 'Dell']
df2.sort_values('Final Price')


Laptop       Status Brand  \
633   Dell Latitude E5440 Intel Core i5-4310U/8GB/12...  Refurbished  Dell   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
809   Dell Latitude E7450 Intel Core i5-5300U/8GB/25...  Refurbished  Dell   
1836  Dell Latitude 5480 Intel Core i5-7300U/8GB/256...  Refurbished  Dell   
1839  Dell Latitude E5550 Intel Core i5-5300U/8GB/12...  Refurbished  Dell   
...                                                 ...          ...   ...   
1323  Dell Latitude 5520 Intel Core i5-1135G7/8GB/25...          New  Dell   
1347  Dell XPS 15 9520 Intel Core i7-12700H/32GB/1TB...  Refurbished  Dell   
1346  Dell XPS 15 9520 Intel Core i7-12700H/16GB RAM...          New  Dell   
1334  Dell Precision 5470 Intel Core i7-12800H/16GB/...          New  Dell   
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...          New  Dell   

          Model            CPU  RAM  Storage Storage type        GPU  Screen  \
633    Latitude  Intel Core i5    8      128          SSD        NaN    14.0   
1843     Vostro  Intel Core i5    8      256          SSD        NaN    13.3   
809    Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
1836   Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
1839   Latitude  Intel Core i5    8      128          SSD        NaN    15.6   
...         ...            ...  ...      ...          ...        ...     ...   
1323   Latitude  Intel Core i5    8      256          SSD        NaN    15.6   
1347        XPS  Intel Core i7   32     1000          SSD   RTX 3050    15.6   
1346        XPS  Intel Core i7   16     1000          SSD   RTX 3050    15.6   
1334  Precision  Intel Core i7   16      512          SSD  RTX A1000    14.0   
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   

     Touch  Final Price  
633     No       379.00  
1843    No       420.74  
809     No       448.99  
1836    No       489.00  
1839    No       489.00  
...    ...          ...  
1323    No      2450.71  
1347   Yes      2818.09  
1346    No      3012.09  
1334    No      3469.00  
1335   Yes      3936.00  

[84 rows x 12 columns]

In [512]:
print("Q5 : 3936")

Q5 : 3936


In [513]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [514]:
print("Median of the screen is", df['Screen'].median(), "inches")

Median of the screen is 15.6 inches


In [515]:
df["Screen"].mode()

0    15.6
Name: Screen, dtype: float64

In [516]:
df['Screen'].fillna(15.6)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [517]:
df['Screen'].median()

np.float64(15.6)

In [518]:
print("Q6 : No")

Q6 : No


In [519]:
df3 = df[df['Brand'] == 'Innjoo']
df3 = df3[["RAM", "Storage", "Screen"]]
df3

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [520]:
X = np.array(df3)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [528]:
Xtr = X.T
XTX = Xtr @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [531]:
invr = np.linalg.inv(XTX)
invr

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [550]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
w = ( invr @ Xtr ) @ y 
print(w.sum())

91.29988062995753


In [551]:
print("Q7 : 91.3")

Q7 : 91.3
