In [303]:
import numpy as np
import pandas as pd

In [ ]:
np_array = np.ones(9)
print(np_array)


np_array_ = np.full(4, 9)
print(np_array_)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 9 9 9]


In [14]:
my_list = [23, 34, 5]
my_list = np.array(my_list)
print(my_list)

[23 34  5]


In [17]:
range_array = np.arange(90)
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [21]:
linspace_array = np.linspace(0,1,3)
linspace_array

array([0. , 0.5, 1. ])

In [27]:
zm = np.full([10, 10], 89)
zm

array([[89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89, 89, 89, 89, 89]])

In [43]:
# slicing function
arr = np.array([[2,3,4], [4, 5, 6]])
print(arr)
arr = arr[1:, 1:]
arr

[[2 3 4]
 [4 5 6]]


array([[5, 6]])

In [296]:
k = np.random.rand(2, 2)
print(k)

m = np.random.randint(0, 10, [2, 2])
print(m)

[[0.15002337 0.83363667]
 [0.13730599 0.45296117]]
[[9 4]
 [8 3]]


In [ ]:
g = m > 5
g

array([[ True, False],
       [ True, False]])

In [302]:
elems = np.random.randint(1, 20, [4, 4])
print(elems)
selected_elements = elems[elems>10]
print(selected_elements)
print(elems.size)

[[ 6 19  4  6]
 [16 16  2  6]
 [ 1  7 10  3]
 [12  5 10 14]]
[19 16 16 12 14]
16


In [311]:


data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

df = pd.DataFrame(data)
df.columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]
df


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [318]:
ser = df['Make']
ser

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [319]:
df[["Make", "Model"]]

Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier

In [320]:
df['id'] = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [321]:
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [323]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [327]:
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [328]:
df.index = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1   Nissan    Stanza  1991      138.0                 4            MANUAL   
2  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3    Lotus     Elise  2010      218.0                 4            MANUAL   
4      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
5   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         sedan   2000  
2         Sedan  27150  
3   convertible  54990  
4       4dr SUV  34450  
5        Pickup  32340

In [329]:
pd.__version__

'2.2.3'